apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName }}-secret
  labels:
    app: {{ .Values.appName }}
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: {{ required "connectionStrings.defaultConnection is required" .Values.connectionStrings.defaultConnection | quote }}
  Jwt__Key: {{ required "jwt.key is required" .Values.jwt.key | quote }}
  Email__SmtpPassword: {{ .Values.email.smtpPassword | quote }}
  TelegramBot__BotToken: {{ .Values.telegramBot.token | quote }}
